 copy D:\deals\Carrington\SMAC\2013-23\Reports\*17Qs.pdf \\ETISERVER\ETISHARE\TOM\Carrington\SMLT\sups_2017\Carrington\*.* /Y
 copy D:\deals\Carrington\SMAC\2014-03\Reports\*17Qs.pdf \\ETISERVER\ETISHARE\TOM\Carrington\SMLT\sups_2017\Carrington\*.* /Y
 copy D:\deals\Carrington\SMAC\2014-05\Reports\*17Qs.pdf \\ETISERVER\ETISHARE\TOM\Carrington\SMLT\sups_2017\Carrington\*.* /Y
 copy D:\deals\Carrington\SMAC\2015-01\Reports\*17Qs.pdf \\ETISERVER\ETISHARE\TOM\Carrington\SMLT\sups_2017\Carrington\*.* /Y
 copy D:\deals\Carrington\SMAC\2015-08\Reports\*17Qs.pdf \\ETISERVER\ETISHARE\TOM\Carrington\SMLT\sups_2017\Carrington\*.* /Y
 copy D:\deals\Carrington\SMAC\2015-09\Reports\*17Qs.pdf \\ETISERVER\ETISHARE\TOM\Carrington\SMLT\sups_2017\Carrington\*.* /Y
 copy D:\deals\Carrington\SMAC\2016-01\Reports\*17Qs.pdf \\ETISERVER\ETISHARE\TOM\Carrington\SMLT\sups_2017\Carrington\*.* /Y
 copy D:\deals\Carrington\SMAC\2016-04\Reports\*17Qs.pdf \\ETISERVER\ETISHARE\TOM\Carrington\SMLT\sups_2017\Carrington\*.* /Y
 copy D:\deals\Carrington\SMAC\2016-21\Reports\*17Qs.pdf \\ETISERVER\ETISHARE\TOM\Carrington\SMLT\sups_2017\Carrington\*.* /Y
 copy D:\deals\Carrington\SMAC\2016-23\Reports\*17Qs.pdf \\ETISERVER\ETISHARE\TOM\Carrington\SMLT\sups_2017\Carrington\*.* /Y
 copy D:\deals\Carrington\SMAC\2016-31\Reports\*17Qs.pdf \\ETISERVER\ETISHARE\TOM\Carrington\SMLT\sups_2017\Carrington\*.* /Y
 copy D:\deals\Carrington\SMAC\2016-32\Reports\*17Qs.pdf \\ETISERVER\ETISHARE\TOM\Carrington\SMLT\sups_2017\Carrington\*.* /Y       